README + tutorial
paraynaud/PartiallySeparableSolvers.jl pull request #11
Opened 2022-07-15 13:45 UTC by paraynaud

2022-07-15 14:07 UTC, paraynaud commented
Show issue of `ExpressionTreeTools`, must be fix with [v0.1.1](https://github.com/JuliaSmoothOptimizers/ExpressionTreeForge.jl/pull/28)

2022-07-15 21:30 UTC, paraynaud commented
@dpo I think the tutorial is ready to be read.

2022-07-19 03:49 UTC, paraynaud commented
@dpo I did apply your remarks, tell me if it is okay for you now.

2022-07-19 14:39 UTC, dpo commented
If I click on "tutorial" on the 1st page, I get a page not found.

2022-07-19 14:54 UTC, dpo requested changes

2022-07-19 14:54 UTC, dpo commented on README.md
> +PartiallySeparableSolvers.jl define partitioned quasi-Newton trust-region solvers for unconstrained `ADNLPModel` or `MathOptNLPModel`.
```suggestion
PartiallySeparableSolvers.jl implements a partitioned quasi-Newton trust-region solvers for unconstrained optimization.
```

2022-07-19 14:54 UTC, dpo commented on README.md
> +The module uses [PartiallySeparableNLPModels.jl](https://github.com/JuliaSmoothOptimizers/PartiallySeparableNLPModels.jl) to detect the partially-separable structure and the structure required to par
```suggestion
The module uses [PartiallySeparableNLPModels.jl](https://github.com/JuliaSmoothOptimizers/PartiallySeparableNLPModels.jl) to detect the partially-separable structure and the structure required for partitioned quasi-Newton approximations.
```

2022-07-19 14:54 UTC, dpo commented on docs/src/index.md
> +PartiallySeparableSolvers.jl define partitioned quasi-Newton trust-region solvers for unconstrained `ADNLPModel` or `MathOptNLPModel`.
```suggestion
PartiallySeparableSolvers.jl implements a partitioned quasi-Newton trust-region solver for unconstrained optimization.
```

2022-07-19 14:54 UTC, dpo commented on docs/src/tutorial.md
> +The usual quasi-Newton updates, such as SR1, BFGS, or their limited-memory variants LSR1 or LBFGS approximate $\nabla^2 f(x)\approx B$ by low rank updates producing inevitably dense approximations.
```suggestion
The usual quasi-Newton updates, such as SR1, BFGS, or their limited-memory variants LSR1 or LBFGS, approximate $\nabla^2 f(x)\approx B$ by low rank updates, which inevitably result in dense approximations.
```

2022-07-19 14:54 UTC, dpo commented on docs/src/tutorial.md
> +By relying on element Hessian approximations $B_i$, updated at each iteration, the partitioned updates respect the Hessian sparsity structure and perform updates of rank $\min(\lambda N,n), \; \lambd
```suggestion
By relying on element Hessian approximations $B_i$ updated at each iteration, the partitioned updates respect the Hessian sparsity structure and perform updates of rank $\min(\lambda N,n), \; \lambda = 1,2$ depending on the update applied to $B_i$.
```

2022-07-19 14:54 UTC, dpo commented on docs/src/tutorial.md
> +See [PartitionedStructures.jl tutorial](https://JuliaSmoothOptimizers.github.io/PartitionedStructures.jl/dev/tutorial/) to get more details about partitioned quasi-Newton approximations and how they
```suggestion
See [PartitionedStructures.jl tutorial](https://JuliaSmoothOptimizers.github.io/PartitionedStructures.jl/dev/tutorial/) for more details about partitioned quasi-Newton approximations and how they compare with standard updates.
```

2022-07-19 14:54 UTC, dpo commented on docs/src/tutorial.md
> +#### Reference
```suggestion

#### Reference
```

2022-07-19 14:54 UTC, dpo commented on docs/src/tutorial.md
> +* A. Griewank and P. Toint, [*Partitioned variable metric updates for large structured optimization problems*](https://link.springer.com/article/10.1007/BF01399316), Numerische Mathematik volume, 39,
```suggestion
* A. Griewank and Ph. L. Toint, [*Partitioned variable metric updates for large structured optimization problems*](https://link.springer.com/article/10.1007/BF01399316), Numerische Mathematik volume, 39, pp. 119--137, 1982.
```

2022-07-19 14:54 UTC, dpo commented on docs/src/tutorial.md
> +For now, PartiallySeparableSolvers.jl supports [ADNLPModel](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl)s, which are defined by pure julia code, or [MathOptNLPModel](https://github.com/Ju
```suggestion
For now, PartiallySeparableSolvers.jl supports [ADNLPModel](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl)s, which are defined by pure julia code, or [MathOptNLPModel](https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl)s, which are based on [JuMP](https://github.com/jump-dev/JuMP.jl) models.
```

2022-07-19 14:54 UTC, dpo commented on docs/src/tutorial.md
> +adnlp_model = example_ADNLPModel(n)
```suggestion
model = ADNLPModel(f, ones(10))
```

2022-07-19 14:54 UTC, dpo commented on docs/src/tutorial.md
> +function example(x)
```suggestion
function f(x)
```

2022-07-19 14:54 UTC, dpo commented on docs/src/tutorial.md
> +stats = PTRUNK(adnlp_model)
```suggestion
stats = PTRUNK(model)
```

2022-07-19 14:54 UTC, dpo commented on docs/src/tutorial.md
> +stats = PTRUNK(adnlp_model)
Montre la sortie du solveur (propre) svp.

2022-07-19 14:54 UTC, dpo commented on docs/src/tutorial.md
> +```@example PSSolver
```suggestion
Thus for example,
```@example PSSolver
```

2022-07-19 14:54 UTC, dpo commented on docs/src/tutorial.md
> +```
```suggestion
```
updates each element Hessian approximation with BFGS.
```

2022-07-19 15:31 UTC, dpo commented on docs/src/tutorial.md
> +stats = PTRUNK(adnlp_model)
Non, le détail des itérations (utilise Trunk comme modèle).

2022-07-19 20:02 UTC, merged